# Generated by Django 2.1.7 on 2023-09-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, verbose_name='ip')),
                ('receive_time', models.DateTimeField(verbose_name='接收时间')),
                ('tem', models.CharField(max_length=20, verbose_name='温度')),
                ('hum', models.CharField(max_length=20, verbose_name='湿度')),
                ('tOpen', models.IntegerField(null=True, verbose_name='温度开关状态')),
                ('hOpen', models.IntegerField(null=True, verbose_name='湿度开关状态')),
            ],
        ),
    ]
